### ISSUE TITLE
"What's new in Wagtail link" in the admin site does not go where it should

### ISSUE THREAD

**Issue by tm-kn** [wagtail/wagtail#12053]
### Issue Summary
In the admin site, I click on "Help" -> "What's new in Wagtail".
The link is https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1/ that redirects to https://guide.wagtail.org/en-latest/.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. `cd myproject`
3. Run `./manage.py migrate`
4. Create a user `./manage.py createsuperuser`
5. Run `./manage.py runserver`
6. Go to http://localhost:8000/admin/.
7. Navigate  "Help" -> "What's new in Wagtail"

It takes me to https://guide.wagtail.org/en-latest/ (link itself is https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1/) which is not the page that I should be taken to.

### Technical details

-   Python version: 3.11.9
-   Django version: 4.2.13
-   Wagtail version: 6.1.2
-   Browser version: Firefox 126

### Working on this

Not sure if this is a problem on https://guide.wagtail.org/ or the Wagtail link is incorrect, so I can't say what's needed.

**Comment by angad-singhh** [comment]
Hey, @tm-kn I'm new to wagtail, if this issue is open for contribution, I would like to take it. If you agree !!
> meanwhile i will try to reproduce this

**Comment by gasman** [comment]
@angad-singhh I think this can only be fixed by someone who has admin access to the guide.wagtail.org site.

@thibaudcolas, please can you investigate?

**Comment by laymonage** [comment]
The link is set here:

https://github.com/wagtail/wagtail/blob/747d70e0656b86e3e8c8d123ecae82fa61cd1438/wagtail/templatetags/wagtailcore_tags.py#L99-L104

Which means it's `https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1/` (note the final slash), but the guide website still uses `en-latest` for 6.1 (the `en-6.1.x` variant isn't going to be made until a newer version is out i.e. 6.2.x). The page actually exists at `https://guide.wagtail.org/en-latest/releases/new-in-wagtail-6-1/`.

On the guide website, I see that we have a redirect for this, but the source URL is set to `https://guide.wagtail.org/en-6.1.x/releases/new-in-wagtail-6-1` (without the slash). You can see that this link correctly redirects to `https://guide.wagtail.org/en-latest/releases/new-in-wagtail-6-1/`.

But we can't update the redirect's source URL to end with a slash due to how Wagtail's redirects work:

https://github.com/wagtail/wagtail/blob/a81cabce058236696e11867e260a771b99417a5e/wagtail/contrib/redirects/models.py#L148-L154

---

The logic to use the version number in the link was added in #11182 but I see that it was also in 6.0, so I'm curious how we handled this for 6.0 (if we did at all). Do you know @thibaudcolas?

**Comment by thibaudcolas** [comment]
For now I’ve created the v6.2 version of the site in the CMS so the link works without a redirect. Will spend more time investigating later in the release cycle.

**Comment by jams2** [comment]
This looks like it's still an issue in 6.3, had a client raise it today. "What's new" link in the help menu links to https://guide.wagtail.org/en-6.3.x/releases/new-in-wagtail-6-3/, which says "Draft". https://guide.wagtail.org/en-latest/releases/new-in-wagtail-6-3/ appears to have the correct content.

**Comment by laymonage** [comment]
Thanks for the report @jams2, I've updated the page.

To prevent this in the future, we need to ensure when an `A.B` release happens, the page at `https://guide.wagtail.org/en-A.B.x/releases/new-in-wagtail-A-B/` must be available and showing the right content. What this entails:
1. Adding `A.B.x` to `WAGTAIL_GUIDE_VERSIONS` in the guide website (e.g. https://github.com/wagtail/guide/commit/b9476248d5db4a4d760d3574f5db25638719c44c).
2. Creating a new "locale" on the guide website for `A.B.x` from the `latest` version.
3. Creating a new page under https://guide.wagtail.org/en-latest/releases/ for the release, "New in Wagtail A.B"
4. Translate the new page to the `en-A.B.x` locale.
5. Ensure both `https://guide.wagtail.org/en-latest/releases/new-in-wagtail-A-B/` and `https://guide.wagtail.org/en-A.B.x/releases/new-in-wagtail-A-B/` are up to date.

Alternatively, we can skip step 1, 2, and 4 by changing the following:

https://github.com/wagtail/wagtail/blob/9889bddcb8823369f7a26c6b6f4a3eb6784d5985/wagtail/templatetags/wagtailcore_tags.py#L103-L104

to:

```diff
     if release == "final":
-        return f"https://guide.wagtail.org/en-{major}.{minor}.x/releases/new-in-wagtail-{major}-{minor}/"
+        return f"https://guide.wagtail.org/en-latest/releases/new-in-wagtail-{major}-{minor}/"
```

which would avoid the issue we had for 6.3. The problem is that this approach would land the user on the "latest" version of the guide, so if they navigated to other pages they might see content that is not applicable to their Wagtail installation.

**Comment by thibaudcolas** [comment]
I believe this is now solved, with the [guide contributing docs](https://guide.wagtail.org/en-latest/contributing/) updated to match what Sage describes above. Now all released versions of Wagtail have their own copy in the guide documentation. I hope this will make more sense for site users – they see the version they’re on in the version picker even if it’s the latest version. If they bookmark a "6.3" page while that version is the latest release, they’ll get to the same page "6.3" page forever.

It’s a bit more work for documentation contributors as the site is set up currently, but we can streamline that easily if we wanted.
