### ISSUE TITLE
Menu: blockOpts is undefined when adding a Streamfield and StreamFieldPanel in a custom MainMenuItem

### ISSUE THREAD

**Issue by robnardo** [wagtail/wagtail#5264]
### Issue Summary

Trying to use Wagtailmenus (and override menu items as per documentation, but getting a JavaScript error: **Uncaught TypeError: Cannot read property 'initializer' of undefined** in stream.js (line 87)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Add the wagtailmenus extension [found here](https://github.com/rkhleics/wagtailmenus).
3. Extend wagtailmenus by adding overrides [as per this link](https://wagtailmenus.readthedocs.io/en/stable/advanced_topics/custom_menu_classes.html#overriding-the-models-used-for-main-menus) , but instead of a CharBlock field add a StreamField (that calls a StructBlock) (example below)
4. Run migrate / makemigrations
5. Visit the admin section and go to Settings > Main menu and click on ADD MENU ITEMS
6. The form should appear with the added StreamField at the bottom - click the icon to create a new StreamField item
7. The JavaScript error will be thrown

### More information

I believe this JavaScript code `var blockTypeName = $('#' + sequenceMember.prefix + '-type').val();` is looking for a hidden field which does not exist in the DOM.

### My Code

``` python
class ManualSubMenuFieldBlock(StructBlock):
    manual_link_url = CharBlock(required=True, max_length=255)
    manual_link_text = CharBlock(required=True, max_length=255)
    class Meta:
        icon = 'form'
        template = "home/blocks/manual_sub_menu_field_block.html"
        label='Manual Sub Items'


# new wagtail custom menu system 
class CustomMainMenuItem(AbstractMainMenuItem):
    """A custom menu item model to be used by ``wagtailmenus.MainMenu``"""

    menu = ParentalKey(
        'wagtailmenus.MainMenu',
        on_delete=models.CASCADE,
        related_name="custom_menu_items", #Add a setting to base.py to use your custom model
    )

    manual_subs = StreamField([
        ('manual_sub_menu', ManualSubMenuFieldBlock()),
    ], null=True, blank=True)

    # Also override the panels attribute, so that the new fields appear
    # in the admin interface

    panels = AbstractMainMenuItem.panels + [
        StreamFieldPanel('manual_subs'),
    ]
```

this setting must be in the base.py (settings) file..

``` python
WAGTAILMENUS_MAIN_MENU_ITEMS_RELATED_NAME = "custom_menu_items"
```

### Technical details

* Python version: 3.6.8
* Django version: 2.1.8
* Wagtail version: 2.4.
* Browser version: Chrome 73

**Comment by robnardo** [comment]
Seems like the DOM element `<input type="hidden" .. >` for type does not get added for some reason?

**Comment by gasman** [comment]
Hi @robnardo,
It looks like this issue is specific to the wagtailmenus extension - please could you open an issue on [the wagtailmenus Github project](https://github.com/rkhleics/wagtailmenus)?

Alternatively, if you can track this down to a Wagtail bug that can be reproduced independently of wagtailmenus, we'll be happy to reopen and investigate further. Thanks!

**Comment by robnardo** [comment]
Hi @gasman - Please reopen this issue.  I am able to reproduce this error using only Wagtail (not installing other modules).  I changed title of this bug since this test involves a StreamField within an InlinePanel.  

Steps to reproduce:

1. Start with a new wagtail install.  My requirements file is:
```
Django>=2.1,<2.2
wagtail==2.5
uwsgi
```

2. Make this the models.py file:
``` python
from django.db import models
from modelcluster.fields import ParentalKey
from wagtail.core import blocks
from wagtail.core.models import Page
from wagtail.core.fields import StreamField
from wagtail.images.blocks import ImageChooserBlock
from wagtail.admin.edit_handlers import InlinePanel, StreamFieldPanel

class HomePage(Page):
    pass

class SubmenuItemsModel(models.Model):
    title = models.CharField(max_length=255)
    submenu_items = StreamField([
        ('submenu_item', blocks.CharBlock()),
    ])

class SubmenusModels(SubmenuItemsModel):
    page = ParentalKey('TestPage', on_delete=models.CASCADE, related_name='submenus_models')

class TestPage(Page):
    content_panels = Page.content_panels + [
        InlinePanel('submenus_models', label="menu items"),
    ]

```
3. Run makemigrations / migrate and reload uwsgi
4. Go to admin the Pages > Home 
5. Choose **ADD A CHILD PAGE** under the Home page and choose the **Test Page** type
6. Then You should get a new Test Page form with Title and Menu Items fields
7. Click the Submenu Item in the StreamField - that will trigger the JavaScript error

![image](https://user-images.githubusercontent.com/12520995/57180801-44afe180-6e5a-11e9-95b6-668a5e7b5459.png)

**Comment by robnardo** [comment]
With the help of a team member of mine, we narrowed down the error to a couple of files:

This file: admin\templates\wagtailadmin\block_forms\stream_member.html
has a couple of hidden input fields that are either being rendered with the wrong "value" or are not being rendered at all

And this file: core\blocks\stream_block.py
which handles rendering of the stream_member template

Winmerge was used to compare and it doesn't show any changes to these files between ver 2.1.3 and 2.2.1.

**Comment by robnardo** [comment]
More digging.. looks like the bug is in one of these files (most likely both). They were both changed in 2.2.1.

wagtail\contrib\settings\templates\wagtailsettings\edit.html
wagtail\admin\templates\wagtailadmin\pages\edit.html

Basically, the line "{{ edit_handler.html_declarations }}" was moved around in the update and is no longer being run. This is causing some html tags to go missing in the final template.

**Comment by gasman** [comment]
Hi @robnardo,

Your `SubmenuItemsModel` needs a `panels` definition, to ensure that the streamfield is being rendered using a `StreamFieldPanel`:

    class SubmenuItemsModel(models.Model):
        title = models.CharField(max_length=255)
        submenu_items = StreamField([
            ('submenu_item', blocks.CharBlock()),
        ])

        panels = [
            FieldPanel('title'),
            StreamFieldPanel('submenu_items'),
        ]

**Comment by robnardo** [comment]
Just to let anyone who uses wagailmenus know - version 2.13.1 of [wagtailmenus](https://pypi.org/project/wagtailmenus/) should fix this issue!

**Comment by tutuca** [comment]
I recently got bit by this. Unfortunately in my case I'm customizing the User model and it looks like it's not using a ModelAdmin or that kind of workflow becasue it's ignoring the panels definition altogether. 
Customizing the `edit.html` and `create.html` templates allows me to render the streamfield but on save it fails with Op's error. I still can't find some way to plug the missing javascript bit.

**Comment by kaedroho** [comment]
I just got bit by this. I accidentally used ``FieldBlock`` instead of ``StreamFieldBlock``.

@gasman  I think if things don't fail in an obvious way, we should add a check so it gives a more useful error message. What do you think?

**Comment by gasman** [comment]
@kaedroho I have a feeling that there's already a mechanism within FieldPanel where the model field can tell it to use a more specific panel class, which is used within RichTextField to avoid the need for an explicit RichTextFieldPanel. This was probably overlooked for StreamField... if so, it's probably about time we rediscovered it and used it :-)
