### ISSUE TITLE
Make it easier to use a custom user model with user create/edit/account settings forms

### ISSUE THREAD

**Issue by brylie** [wagtail/wagtail#7410]
### Is your proposal related to a problem?

When a project creates a custom user model where `first_name` and `last_name` are optional, the Wagtail forms still display the fields as being required. In order to make the form fields optional, the developer must override the `WAGTAIL_USER-EDIT_FORM` and `WAGTAIL_USER_CREATION_FORM` with custom-defined models. They must also somehow override the Account Settings form for the user profile section (which I am still not clear how to do).

At the very least, the process is somewhat ambiguous, despite the available documentation:

- https://docs.wagtail.io/en/stable/advanced_topics/customisation/custom_user_models.html
- https://docs.wagtail.io/en/stable/advanced_topics/customisation/custom_account_settings.html

### Describe the solution you'd like

Ideally, the forms would introspect the custom user model to determine whether the fields are required. Furthermore, it might be good to simplify the development process and just allow the user to specify a list of fields to render in the forms rather than creating three custom forms (create/edit/account settings).

### Describe alternatives you've considered

The documentation could be improved around how to customize the user account settings form.

### Additional context

We have a downstream issue where it became apparent how confusing it is to make changes to the user create and edit forms:
- https://github.com/brylie/wagtail-social-network/issues/18

I am also trying to customize the user account settings form to make the fields optional and finding myself at a loss as to how to proceed.

**Comment by brylie** [comment]
After digging in a bit more in our downstream issue, @Upasanadhameliya mentions:

> https://github.com/wagtail/wagtail/blob/b349ba436eeb853a8c2b2ff749f173a1f7d26d59/wagtail/admin/views/account.py#L205
>
> In the link above. they are providing the functionality of adding extra panels to the existing panels as written in the [documentation](https://docs.wagtail.io/en/stable/advanced_topics/customisation/custom_account_settings.html). However they haven't provided the code to modify existing panels.

**Comment by helderco** [comment]
Yes, my user model has a single `name`, not `first_name` and `last_name`. When the account view was multiple forms, I used the `construct_account_menu_items` hook to modify the url for the change name view.

How do I replace/modify the `NameEmailSettingsPanel` now? The only solution I can see is to override the entire `wagtail.admin.views.account.account` view, which is I hope is temporary until someone adds the ability to change these panels.

**Comment by helderco** [comment]
If at least `django.contrib.auth.base_user.AbstractBaseUser.REQUIRED_FIELDS`is respected in making these fields optional, then I can use css to hide first_name and last_name, although it's not ideal.

**Comment by helderco** [comment]
There's already a `settings.WAGTAIL_USER_CUSTOM_FIELDS`, used in `wagtail.users.forms.UserCreationForm` and `wagtail.users.forms.UserEditForm`, so fixing `wagtail.admin.forms.account.NameEmailForm` is easy.

**Comment by brylie** [comment]
@helderco, could you give an example of using WAGTAIL_USER_CUSTOM_FIELDS to customize the UserCreationForm and UserEditForm? Resolving this issue might only need an update to the Wagtail docs.

cc: @gasman

**Comment by helderco** [comment]
No, not the docs. The current `wagtail.admin.forms.account.NameEmailForm` would have to be adapted to support `settings.WAGTAIL_USER_CUSTOM_FIELDS` and `django.contrib.auth.base_user.AbstractBaseUser.REQUIRED_FIELDS`.

**Comment by helderco** [comment]
I've just realised that I'm using my own overrides in `settings.WAGTAIL_USER_EDIT_FORM` and `settings.WAGTAIL_USER_CREATION_FORM` because the default form (`wagtail.users.forms.UserEditForm`) adds the fields `settings.WAGTAIL_USER_CUSTOM_FIELDS`, it doesn't replace the default `first_name` and `last_name`fields.

**Comment by robslotboom** [comment]
Same problem here.
Our userModel has an extra field for “suffix” because Dutch names can look like Jan van Schaffelaar.
So this field should show up in the NameEmailPanel.

The only possible way to achive this is to override the comlete view...

**Comment by shapiromatron** [comment]
I'm having the same issue as above; having a hard time modifying (or even removing) the `NameEmailSettingsPanel`

**Comment by shapiromatron** [comment]
Found hack, though it's not ideal. In the app ready signal:

```python
from django.apps import AppConfig


class MyApp(AppConfig):
    def ready(self) -> None:
        from wagtail.admin.views.account import NameEmailSettingsPanel

        NameEmailSettingsPanel.is_active = lambda self: False
        return super().ready()
```

This cases this panel to be filtered out (see [source](https://github.com/wagtail/wagtail/blob/b7beb36df6bc89e6152eae6c7d2dabaee7bd660a/wagtail/admin/views/account.py#L262)).

**Comment by brylie** [comment]
This would be a good addition to the Wagtail Docs, under "Customizing the Settings Menu: Removing or Modifying User Settings Panel" or something similar :-)

**Comment by shapiromatron** [comment]
@brylie PR submitted! #11670

**Comment by perepicornell** [comment]
Hi!
Just having trouble because our app does not include the `last_name` field in the `User` model. I imagine that following [this documentation](https://docs.wagtail.org/en/stable/advanced_topics/customisation/custom_user_models.html) I should solve this, and I'll try, but it looked like so much of a hassle for something that's probably a common use case, that I ended up here when looking for simpler ways to solve it.

The current behavior that I'm trying to solve is that when a user edits its own profile, there's the "Last name" field (required) which obviously doesn't display it (we don't have it in the model) neither it saves it.

Same would happen when adding or editing other users ofc, but we've removed the access to Users and Groups altogether because we want them to manage that in the django's admin panel.

I hope this is information is useful, and thank you very much!

**Comment by laymonage** [comment]
Thank you @perepicornell for raising it again. I think this issue is still valid. Our docs say that:

> "The custom user model must at minimum inherit from [`AbstractBaseUser`](https://docs.djangoproject.com/en/stable/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser) and [`PermissionsMixin`](https://docs.djangoproject.com/en/stable/topics/auth/customizing/#django.contrib.auth.models.PermissionsMixin)."

Yet the following code:

https://github.com/wagtail/wagtail/blob/246f3c7eb542be2081556bf5334bc22256776bf4/wagtail/users/forms.py#L29-L30

incorrectly expects `email`, `first_name`, `last_name`, all of which come from `AbstractUser` (not `AbstractBaseUser`). 

`is_superuser` and `groups` come from `PermissionsMixin`, which we already state as required, so they're OK.

I think we should change `standard_fields` so that it only adds those three fields when they are available on the user model.

**Comment by OdifYltsaeb** [comment]
Came here to complain how user model field names are hardcoded into codebase instead of allowing user to configure them via settings or just discovering them from get_user_model.fields() or something... Only to find that this topic has been open for 4 years already.

Ugh. +1 to everyone else here. And -1 to the documentation suggesting overriding numerous things to get user views working.... instead of not making these things hardcoded in the first place.

BTW if you do not want to go through trouble of overriding all the things as suggested by [this page](https://docs.wagtail.org/en/stable/advanced_topics/customization/custom_user_models.html), then you can do what I did and just add a hack on your UserManager, so that visiting /cms/users/ does no longer in error 50, go ahead and add this to your UserManager:


```
    def get_queryset(self):
        # Provide virtual fields expected by some admin/Wagtail views
        # that order by 'last_name' / 'first_name'. We don't store these
        # in DB; we annotate them from our single 'name' field so that
        # order_by("last_name", "first_name") works without schema changes.
        return (
            UserQuerySet(self.model, using=self._db)
            .annotate(
                last_name=F("name"),
                first_name=Value("", output_field=CharField()),
            )
        )
```
