### ISSUE TITLE
comments icon overlap with field help text

### ISSUE THREAD

**Issue by minusf** [wagtail/wagtail#7715]
### Issue Summary

Just after the `1200px` breakpoint there is a small window where the higher `z-index` `object-help` eclipses the comment icon: (notice the non-clickable mouse cursor)

![comment-icon](https://user-images.githubusercontent.com/3632883/142236522-45199978-c9da-40dd-992d-1acd449dd534.png)

I am not sure about the solution but i think i would prefer the comment icon not to dance around based on window width but always stay near the edge:

```
M client/scss/components/_forms.scss
@@ -463,10 +463,6 @@ li.inline:first-child {
 
         &--object {
             right: 20px;
-
-            @include media-breakpoint-up(lg) {
-                right: 350px;
-            }
         }
 
         button {
```

<img width="472" alt="Screenshot 2021-11-17 at 17 09 14" src="https://user-images.githubusercontent.com/3632883/142237345-046e892d-d000-4ccc-9004-9f95cea908ce.png">

### Steps to Reproduce

1. enable comments
2. shrink window

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.9.8
* Django version: 3.2.9
* Wagtail version: 2.15.1
* Browser version: any

**Comment by halinh0507** [comment]
@minusf I tried to reproduce the bug but when I shrink the window, the comment icon and the page look different from the screenshot above. Is this page where the issue happens?
![image](https://user-images.githubusercontent.com/54815653/151606914-8f58006b-f42e-43ef-9839-8adaedb5dd45.png)

**Comment by lb-** [comment]
@thibaudcolas this is in the status fixed for the page editor 2022 but issue is not closed. 

Can you confirm this is fixed?
Maybe @stevedya

**Comment by minusf** [comment]
sorry for dropping this, after the security issue with this feature comments were turned off in our project and so far nobody is missing it too much, so we didn't turn it back on.

but to answer your questions @halinh0507, yes the issue is on that page.  however you need to turn on the commenting feature to see the "add comment" icons for every form entry item. my screenshot shows the "+" for the "Title" input, and depending on the type of input, content of `help_text` fields and others the icon might be shown in various ways.  but i could reproduce it easily with the Title one.

**Comment by gasman** [comment]
Pretty sure this is fixed in the 3.0 redesign - the comment icon remains clickable and well away from the help text at all window sizes.
![Screenshot 2022-06-20 at 14 03 35](https://user-images.githubusercontent.com/85097/174608279-432353cc-7aa9-4181-9348-ffaa6a71f65b.png)

**Comment by gasman** [comment]
Retested (on Chrome and Firefox), and I can confirm that the overlap still happens at sizes just above 1200px on both 3.0.1 and current main.

**Comment by thibaudcolas** [comment]
This has been addressed in #8921, which will be released in Wagtail 4.
